# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pai-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pai"
s3_prefix = "pai-stack"
region = "us-east-1"
template_file = "template.yaml"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
